dromara:
  x-file-storage:
    default-platform: aliyun-oss-1
    thumbnail-suffix: "_thumbnail.jpg"
    aliyun-oss:
      - platform: aliyun-oss-1
        enable-storage: true
        access-key:
        secret-key:
        end-point: oss-cn-hangzhou.aliyuncs.com
        bucket-name: my-bilibili-project
        domain: https://my-bilibili-project.oss-cn-hangzhou.aliyuncs.com/
        base-path:
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
file-folder:
  local:
    video: E:/bilibili/video/
  oss:
    video: video/
    image: image/
system:
  setting:
    register-coin-count: 10
    post-video-coin-count: 10
    video-size: 10485760
    video-p-count: 10
    video-count: 10
    comment-count: 10
    danmu-count: 20
