server:
  port: 7070
  servlet:
    context-path: /admin
spring:
  file-storage: #文件存储配置
    thumbnail-suffix: ".thumbnali.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    aliyun-oss:
      - platform: bilibili-back # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${ALIYUN_ACCESS_KEY}
        secret-key: ${ALIYUN_SECRET_KEY}
        end-point: ${ALIYUN_END_POINT}
        bucket-name: bilibili-back
        domain: ${ALIYUN_DOMAIN}
        base-path: category/ # 基础路径
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      location: C:/Study/temp # 更改为有写入和删除权限的目录
  application:
    name: bilibili-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bilibili?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: zbt041205
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
mybatis-plus:
  type-aliases-package: com.bilibili.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
project:
  folder: c:/Study/webser/easylive/
log:
  root:
    level: debug
admin:
  account: admin
  password: admin123
